---
title: "02_get_gbif"
author: "Dexter H. Locke, PhD"
date: "`r format(Sys.time())`"
output: html_document
editor_options: 
  chunk_output_type: console
---

based off of Millie's "holc-all-spp.R" but designed for laptop

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# 0 set up: load libraries, custom functions, set defaults
```{r}

# load libraries
# packages we'll be using
packs <- c(
    'tidyverse'  # a must have
  , 'gbifdb' # GBIF
  # , 'fst' # a faster table 
  # , 'terra'
  , 'sf'              # spatial support
  , 'mapview'         # webmaps
  , 'janitor'   # cleans things up, also pipe-friendly cross-tabulations
  , 'tictoc'          # times things
  , 'beepr'           # makes noises
)


# check for all of the libraries, install if you don't have them
if (length(setdiff(packs, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packs, rownames(installed.packages())))  
}

# load them
vapply(packs, library, character.only = TRUE, logical(1), logical.return = TRUE, quietly = TRUE)



# set custom function for getting spatial data
see_sf <- function(){
# what's in memory that are sf - spatial features?
keep(eapply(.GlobalEnv, class),      # gets the objects in the global environment
     ~ any(str_detect(., "sf"))) %>% # selects elements with sf in them
    names(.) %>% as.character(.)     # my simple features
}

see_sf() -> sf_in_memory

# what are the spatial references of those SF classes?
mget(sf_in_memory) %>% purrr::map(~st_crs(.x)$epsg) %>% unlist() #%>% View()


# # get file size
# for(obj in ls()){message(obj); print(object.size(get(obj)), units='auto'); cat('\n')}; rm(obj)

# thanks Phil Donovan @philip_donovan
# https://www.spatialanalytics.co.nz/post/2018/04/01/fixing-st-par/
# Paralise any simple features analysis.
st_parallel <- function(sf_df, sf_func, n_cores, ...){

  # Create a vector to split the data set up by.
  split_vector <- rep(1:n_cores, each = nrow(sf_df) / n_cores, length.out = nrow(sf_df))

  # Perform GIS analysis
  split_results <- split(sf_df, split_vector) %>%
    parallel::mclapply(function(x) sf_func(x, ...), mc.cores = n_cores)


  # Define the output_class. If length is greater than two, then grab the second variable.
  output_class <- class(split_results[[1]])
  if (length(output_class) == 2){
    output_class <- output_class[2]
  }

  # Combine results back together. Method of combining depends on the output from the function.
  if (output_class == "matrix"){
    result <- do.call("rbind", split_results)
    names(result) <- NULL
  } else if (output_class == "sfc") {
    result <- do.call("c", split_results)
    result <- sf_func(result) # do.call combines the list but there are still n_cores of the geometry which had been split up. Running st_union or st_collect gathers them up into one, as is the expected output of these two functions.
  } else if (output_class %in% c('list', 'sgbp') ){
    result <- do.call("c", split_results)
    names(result) <- NULL
  } else if (output_class == "data.frame" ){
    result <- do.call("rbind", split_results)
  } else {
    stop("Unknown class. st_parallel only accepts the following outputs at present: sfc, list, sf, matrix, sgbp.")
  }

  # Return result
  return(result)
}


# custom function for "Not In"
`%nin%` <- Negate(`%in%`)



# fixes mapview
mapviewOptions(fgb = FALSE)

```

# 1 connectd to database
```{r}

db <- gbif_remote()
# # I use a local version of gbif but should work as well with the above code
# # db <- gbif_remote(bucket="gbif", 
# #                   endpoint_override = "minio.cirrus.carlboettiger.info", 
# #                   version="2022-03-01")
# 
```

# 2 sample query - sandbox for working out the queries
```{r eval=FALSE, include=FALSE}
# # works
# # grab all occurances in US, count by lat long and class of app
# tic(); US_spp <- db |>
#   filter(countrycode == "US") |>
#   count(class, decimallatitude, decimallongitude) |>
#   collect(); toc(); beep() # ~15 mins
# 
# TIP: load up count with year, collectionCode, institutionCode, basisofrecord then filter?
# 
# # what are the column names available?
# tic(); (test_col_names <- 
#   db |>
#   filter(countrycode == "US") |> 
#   names()); toc(); beep() # lightening fast, nano seconds
# 
# # DOES NOT WORK - don't know the values for stateprovince!
# tic(); (test_download <- 
#   db |>
#   filter(countrycode == "US") |> 
#   filter(stateprovince == "RI") |> 
#   collect()); toc(); beep() # 40 mins and empty

class_to_keep <- c('Aves', 'Insecta', 'Mammalia', 'Reptilia', 'Amphibia')
tic(); (test_download <- 
          db |>
          filter(countrycode == "US") |> 
          select(
              # kingdom - needed?
              class
            , year
            , basisofrecord    # to drop 'unknown'?
            , collectioncode   # has GBBC, which is ebird, has EBIRD which is ebird
            , institutioncode  # has iNaturalist
            , decimallatitude, decimallongitude
            ) |>
          filter(year >= 2000 & year <= 2020) |> # recent, please
          filter(class %in% class_to_keep) |>    # only classes of interest
          filter(!is.na(decimallatitude) & !is.na(decimallongitude)) |> # need coords
          # combine/reclass data provider here?
          count(  class
                , year
                , basisofrecord
                , collectioncode
                , institutioncode
                , decimallatitude, decimallongitude
                ) |> 
          collect()
        ); toc(); beep() # 36 mins without count, ~9 mins with count
test_download |> distinct(basisofrecord)
test_download |> distinct(collectioncode)
test_download |> distinct(institutioncode)
test_download |> 
  as_tibble() |> 
  write_csv(paste0(getwd()
                   , "/working_data/gbif_download/" # should write to large file directory not for sharing
                   , 'test_'
                   , Sys.Date()
                   , '.csv')
            )
# # try to write out?
# test_download |> 
#   fst::write_fst(
#     paste0(getwd(), "/working_data/gbif_download/test_download.fst"))
# 
# 
# (test_download <- fst::read.fst("test_download.fst") |> tibble())
# 
# 
# (test_download <- fst::read.fst(paste0(getwd(), "/working_data/gbif_download/test_download.fst")) |> tibble())
```

## A PLANTS
```{r eval=FALSE, include=FALSE}

# keep_king <- c('Plantae', 'Fungi')
# keep_class<- c('Aves', 'Insecta', 'Mammalia', 'Reptilia', 'Amphibia')

tic(); (download_plantae <- 
          db |>
          filter(countrycode == "US") |> 
          select(
              kingdom
            , class
            , genus
            , species
            , year
            # , basisofrecord    # to drop 'unknown'?
            , collectioncode   # has GBBC, which is ebird, has EBIRD which is ebird
            , institutioncode  # has iNaturalist
            , decimallatitude, decimallongitude
            ) |>
          filter(year >= 2000 & year <= 2020) |> # recent, please
          # king/classes of interest
          filter(kingdom == 'Plantae') |> 
          filter(!is.na(decimallatitude) & !is.na(decimallongitude)) |> # need coords
          mutate(source = 
                   case_when(
                     str_detect(collectioncode, 'EBIRD')  ~  'ebird',
                     str_detect(institutioncode, 'iNaturalist') ~ 'iNaturalist',
                     TRUE ~ 'other')
                 ) |> 
          count(  #class # TODO I'm not confident a nice kingdom/class look up to genus/species will be available.. keep here?
              genus
            , species
            , year
            # , basisofrecord
            # , collectioncode
            # , institutioncode
            , source
            , decimallatitude, decimallongitude
            , name = 'n_obs'
                ) |> 
          collect()
        ); toc(); beep() # ~5 mins

# a few double checks
download_plantae # ~8.5M records
download_plantae |> glimpse()
download_plantae |> tabyl(year)   # growing over time
download_plantae |> tabyl(source) # ~61% from iNaturalist
download_plantae |> tabyl(n_obs)
download_plantae |> arrange(desc(n_obs))

# # write it out ~0.5Gb
# download_plantae |> 
#   write_csv(paste0('../biodiversity_in_a_concrete_jungle_data_too_big/download_plantae_'
#             , Sys.Date()
#             , '.csv'
#             ))
# rm(download_plantae)
```


## B FUNGI
```{r eval=FALSE, include=FALSE}

# keep_king <- c('Plantae', 'Fungi')
# keep_class<- c('Aves', 'Insecta', 'Mammalia', 'Reptilia', 'Amphibia')

tic(); (download_fungi <- 
          db |>
          filter(countrycode == "US") |> 
          select(
              kingdom
            , class
            , genus
            , species
            , year
            # , basisofrecord    # to drop 'unknown'?
            , collectioncode   # has GBBC, which is ebird, has EBIRD which is ebird
            , institutioncode  # has iNaturalist
            , decimallatitude, decimallongitude
            ) |>
          filter(year >= 2000 & year <= 2020) |> # recent, please
          # king/classes of interest
          filter(kingdom == 'Fungi') |> 
          filter(!is.na(decimallatitude) & !is.na(decimallongitude)) |> # need coords
          mutate(source = 
                   case_when(
                     str_detect(collectioncode, 'EBIRD')  ~  'ebird',
                     str_detect(institutioncode, 'iNaturalist') ~ 'iNaturalist',
                     TRUE ~ 'other')
                 ) |> 
          count(  #class # TODO I'm not confident a nice kingdom/class look up to genus/species will be available.. keep here?
              genus
            , species
            , year
            # , basisofrecord
            # , collectioncode
            # , institutioncode
            , source
            , decimallatitude, decimallongitude
            , name = 'n_obs'
                ) |> 
          collect()
        ); toc(); beep() # ~5 mins

# a few double checks
download_fungi # ~1M records
download_fungi |> glimpse()
download_fungi |> tabyl(year)
download_fungi |> tabyl(source)
download_fungi |> tabyl(n_obs)
download_fungi |> arrange(desc(n_obs))

# # write it out
# download_fungi |> # ~62Mb
#   write_csv(paste0('../biodiversity_in_a_concrete_jungle_data_too_big/download_fungi_'
#             , Sys.Date()
#             , '.csv'
#             ))
# rm(download_fungi)
```


## C AVES - too big?
```{r}

# keep_king <- c('Plantae', 'Fungi')
# keep_class<- c('Aves', 'Insecta', 'Mammalia', 'Reptilia', 'Amphibia')

tic(); (download_aves <- 
          db |>
          filter(countrycode == "US") |> 
          select(
              kingdom
            , class
            , genus
            , species
            , year
            # , basisofrecord    # to drop 'unknown'?
            , collectioncode   # has GBBC, which is ebird, has EBIRD which is ebird
            , institutioncode  # has iNaturalist
            , decimallatitude, decimallongitude
            ) |>
          filter(year >= 2000 & year <= 2020) |> # recent, please
          # king/classes of interest
          filter(class == 'Aves') |> 
          filter(!is.na(decimallatitude) & !is.na(decimallongitude)) |> # need coords
          mutate(source = 
                   case_when(
                     str_detect(collectioncode, 'EBIRD')  ~  'ebird',
                     str_detect(institutioncode, 'iNaturalist') ~ 'iNaturalist',
                     TRUE ~ 'other')
                 ) |> 
          count(  #class # TODO I'm not confident a nice kingdom/class look up to genus/species will be available.. keep here?
              genus
            , species
            # , year    # NOTICE THIS IS TURNED OFF
            # , basisofrecord
            # , collectioncode
            # , institutioncode
            , source
            , decimallatitude, decimallongitude
                ) |> 
          collect()
        ); toc(); beep() # ~tk mins

# a few double checks
download_aves
download_aves |> glimpse()
download_aves |> tabyl(year)
download_aves |> tabyl(source)
download_aves |> tabyl(n)

# write it out
download_aves |> 
  write_csv(paste0('../biodiversity_in_a_concrete_jungle_data_too_big/download_aves_no_year_'
            , Sys.Date()
            , '.csv'
            ))

```


## D INSECTA
```{r eval=FALSE, include=FALSE}

# keep_king <- c('Plantae', 'Fungi')
# keep_class<- c('Aves', 'Insecta', 'Mammalia', 'Reptilia', 'Amphibia')

tic(); (download_insecta <- 
          db |>
          filter(countrycode == "US") |> 
          select(
              kingdom
            , class
            , genus
            , species
            , year
            # , basisofrecord    # to drop 'unknown'?
            , collectioncode   # has GBBC, which is ebird, has EBIRD which is ebird
            , institutioncode  # has iNaturalist
            , decimallatitude, decimallongitude
            ) |>
          filter(year >= 2000 & year <= 2020) |> # recent, please
          # king/classes of interest
          filter(class == 'Insecta') |> 
          filter(!is.na(decimallatitude) & !is.na(decimallongitude)) |> # need coords
          mutate(source = 
                   case_when(
                     str_detect(collectioncode, 'EBIRD')  ~  'ebird',
                     str_detect(institutioncode, 'iNaturalist') ~ 'iNaturalist',
                     TRUE ~ 'other')
                 ) |> 
          count(  #class # TODO I'm not confident a nice kingdom/class look up to genus/species will be available.. keep here?
              genus
            , species
            , year
            # , basisofrecord
            # , collectioncode
            # , institutioncode
            , source
            , decimallatitude, decimallongitude
            , name = 'n_obs'
            ) |> 
          collect()
        ); toc(); beep() # ~6 mins

# a few double checks
download_insecta # ~4.1M records
download_insecta |> glimpse()
download_insecta |> tabyl(year) # growth over time..
download_insecta |> tabyl(source) # 70% iNat
download_insecta |> tabyl(n_obs)
download_insecta |> arrange(desc(n_obs))

# # write it out, ~27Mb
# download_insecta |> 
#   write_csv(paste0('../biodiversity_in_a_concrete_jungle_data_too_big/download_insecta_'
#             , Sys.Date()
#             , '.csv'
#             ))
# rm(download_insecta)
```


## E MAMMALIA
```{r eval=FALSE, include=FALSE}

# keep_king <- c('Plantae', 'Fungi')
# keep_class<- c('Aves', 'Insecta', 'Mammalia', 'Reptilia', 'Amphibia')

tic(); (download_mammalia <- 
          db |>
          filter(countrycode == "US") |> 
          select(
              kingdom
            , class
            , genus
            , species
            , year
            # , basisofrecord    # to drop 'unknown'?
            , collectioncode   # has GBBC, which is ebird, has EBIRD which is ebird
            , institutioncode  # has iNaturalist
            , decimallatitude, decimallongitude
            ) |>
          filter(year >= 2000 & year <= 2020) |> # recent, please
          # king/classes of interest
          filter(class == 'Mammalia') |> 
          filter(!is.na(decimallatitude) & !is.na(decimallongitude)) |> # need coords
          mutate(source = 
                   case_when(
                     str_detect(collectioncode, 'EBIRD')  ~  'ebird',
                     str_detect(institutioncode, 'iNaturalist') ~ 'iNaturalist',
                     TRUE ~ 'other')
                 ) |> 
          count(  #class # TODO I'm not confident a nice kingdom/class look up to genus/species will be available.. keep here?
              genus
            , species
            , year
            # , basisofrecord
            # , collectioncode
            # , institutioncode
            , source
            , decimallatitude, decimallongitude
            , name = 'n_obs'
                ) |> 
          collect()
        ); toc(); beep() # ~5 mins

# a few double checks
download_mammalia # ~1M records
download_mammalia |> glimpse()
download_mammalia |> tabyl(year)   # not *every* year has more than prior yer!
download_mammalia |> tabyl(source) # ~42% iNat
download_mammalia |> tabyl(n_obs)
download_mammalia |> arrange(desc(n_obs))

# # write it out, ~70Mb
# download_mammalia |> 
#   write_csv(paste0('../biodiversity_in_a_concrete_jungle_data_too_big/download_mammalia_'
#             , Sys.Date()
#             , '.csv'
#             ))
# rm(download_mammalia)
```


## F REPTILIA - empty?
```{r}

# keep_king <- c('Plantae', 'Fungi')
# keep_class<- c('Aves', 'Insecta', 'Mammalia', 'Reptilia', 'Amphibia')

tic(); (download_reptilia <- 
          db |>
          filter(countrycode == "US") |> 
          select(
              kingdom
            , class
            , genus
            , species
            , year
            # , basisofrecord    # to drop 'unknown'?
            , collectioncode   # has GBBC, which is ebird, has EBIRD which is ebird
            , institutioncode  # has iNaturalist
            , decimallatitude, decimallongitude
            ) |>
          filter(year >= 2000 & year <= 2020) |> # recent, please
          # king/classes of interest
          filter(class == 'Reptilia') |> 
          filter(!is.na(decimallatitude) & !is.na(decimallongitude)) |> # need coords
          mutate(source = 
                   case_when(
                     str_detect(collectioncode, 'EBIRD')  ~  'ebird',
                     str_detect(institutioncode, 'iNaturalist') ~ 'iNaturalist',
                     TRUE ~ 'other')
                 ) |> 
          count(  #class # TODO I'm not confident a nice kingdom/class look up to genus/species will be available.. keep here?
              genus
            , species
            , year
            # , basisofrecord
            # , collectioncode
            # , institutioncode
            , source
            , decimallatitude, decimallongitude
            , name = 'n_obs'
                ) |> 
          collect()
        ); toc(); beep() # ~5 mins

# a few double checks
download_reptilia
download_reptilia |> glimpse()
download_reptilia |> tabyl(year)
download_reptilia |> tabyl(source)
download_reptilia |> tabyl(n_obs)
download_reptilia |> arrange(desc(n_obs))

# write it out
download_reptilia |> 
  write_csv(paste0('../biodiversity_in_a_concrete_jungle_data_too_big/download_reptilia_'
            , Sys.Date()
            , '.csv'
            ))
rm(download_reptilia)
```


## G AMPHIBIA
```{r}

# keep_king <- c('Plantae', 'Fungi')
# keep_class<- c('Aves', 'Insecta', 'Mammalia', 'Reptilia', 'Amphibia')

tic(); (download_amphibia <- 
          db |>
          filter(countrycode == "US") |> 
          select(
              kingdom
            , class
            , genus
            , species
            , year
            # , basisofrecord    # to drop 'unknown'?
            , collectioncode   # has GBBC, which is ebird, has EBIRD which is ebird
            , institutioncode  # has iNaturalist
            , decimallatitude, decimallongitude
            ) |>
          filter(year >= 2000 & year <= 2020) |> # recent, please
          # king/classes of interest
          filter(class == 'Amphibia') |> 
          filter(!is.na(decimallatitude) & !is.na(decimallongitude)) |> # need coords
          mutate(source = 
                   case_when(
                     str_detect(collectioncode, 'EBIRD')  ~  'ebird',
                     str_detect(institutioncode, 'iNaturalist') ~ 'iNaturalist',
                     TRUE ~ 'other')
                 ) |> 
          count(  #class # TODO I'm not confident a nice kingdom/class look up to genus/species will be available.. keep here?
              genus
            , species
            , year
            # , basisofrecord
            # , collectioncode
            # , institutioncode
            , source
            , decimallatitude, decimallongitude
            , name = 'n_obs'
                ) |> 
          collect()
        ); toc(); beep() # ~6 mins

# a few double checks
download_amphibia # ~300k records
download_amphibia |> glimpse()
download_amphibia |> tabyl(year)
download_amphibia |> tabyl(source) # 87% iNaturalist
download_amphibia |> tabyl(n_obs)
download_amphibia |> arrange(desc(n_obs))

# # write it out, ~21Mb
# download_amphibia |> 
#   write_csv(paste0('../biodiversity_in_a_concrete_jungle_data_too_big/download_amphibia_'
#             , Sys.Date()
#             , '.csv'
#             ))
# rm(download_amphibia)


```

## End