---
title: "pull density completeness together"
author: "Dexter H. Locke, PhD"
date: "`r format(Sys.time())`"
output: html_document
editor_options: 
  chunk_output_type: console
---

TODO send files that did not complete runing the completness

look at plant query


<!-- what about a total? run again without taxon breaks - going to blow out RAM -->


<!-- split by source! educational opportunities via iNat-->

<!-- double check plant downloads, lots of data? -->

<!-- high completeness, filter and drill down into ? ONLY Look at richness when completeness is high -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# 0 set up: load libraries, custom functions, set defaults
```{r}

# load libraries
# packages we'll be using
packs <- c(
    'tidyverse'  # a must have
  , 'tidylog'    # prints out what was done in dplyr and tidr
  # , 'gbifdb' # GBIF
  # , 'fst' # a faster table, makes outputs files much smaller, too.
  # , 'terra'
  # , 'KnowBR'    # creates biodiversity estimates like completeness.
  # , 'tidycensus'      # Census access
  , 'sf'        # spatial support
  , 'mapview'   # webmaps
  , 'janitor'   # cleans things up, also pipe-friendly cross-tabulations
  , 'tictoc'    # times things
  , 'beepr'     # makes noises
)


# check for all of the libraries, install if you don't have them
if (length(setdiff(packs, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packs, rownames(installed.packages())))  
}

# load them
vapply(packs, library, character.only = TRUE, logical(1), logical.return = TRUE, quietly = TRUE)



# custom function for "Not In"
`%nin%` <- Negate(`%in%`)


# redlining colors
holc_pal <- c('#92BC6B' # green
              , '#92C7C9' # blue
              , '#E7DC6B' # yellow
              , '#E47D67' # red
              #, '#A9A9A9'
              ) # dark gray)

holc_pal_f<- c('#92BC6B' # green
              , '#92C7C9' # blue
              , '#E7DC6B' # yellow
              , '#E47D67' # red
              , '#A9A9A9'
              , '#000000')

# fixes mapview
mapviewOptions(fgb = FALSE)
```



# read in data

```{r}

# setwd('_students/Diego/biodiversity_in_a_concrete_jungle/working_data/')
getwd()


(holc <- st_read('working_data/holc_polys_saved/holc_plys_2022-12-08 20-13-17.gpkg', as_tibble = TRUE) |> 
    filter(st_is(geom, 'POLYGON')) |> 
    select(id, holc_grade, area_holc_km2) |> 
    st_drop_geometry())

holc |> dim()
# list.files('_students/Diego/biodiversity_in_a_concrete_jungle/working_data/')

list.files()

# HOLC completeness and sampling density
holc_comp <-
  tibble(  filename = list.files('working_data/completeness', full.names = TRUE, recursive = TRUE, pattern = 'Estimators.CSV')
         , file_contents = map(filename, ~read_csv(., col_types = cols()))) |> 
  mutate(taxon = str_remove(filename, 'working_data/completeness/') |> 
           str_remove('/Estimators.CSV') |> 
           str_remove('_only') |> 
           str_remove('_graded')) |> 
  select(taxon, file_contents) |> 
  separate(taxon, into = c('taxon', 'level')) |> 
  mutate(level = ifelse(is.na(level), 'species', level)) |> 
  unnest(file_contents) |> 
  right_join(holc, by = c('Area' = 'id')) |> 
  # NA to zero on completeness
  mutate(density = Records / area_holc_km2) |>  
  left_join(read_csv('working_data/MSA/holc_msa_keys_2022-12-08 15-35-19.csv', col_types = 'cc') # makes type = character
            , by = c('Area' = 'id')
  ) |> 
  left_join(read_csv('working_data/MSA_UA_lookup.csv') |> 
              mutate(msa_GEOID = as.character(msa_GEOID)) |> 
              select(msa_GEOID, ua_GEOID)
            , by = 'msa_GEOID') |> 
  select(id = Area, density, completeness = Completeness, pred_richness = Richness, holc_grade, taxon, level, ua_GEOID, msa_GEOID) # cosmetic reorder
# interaction(grade, family?)

# TODO figure out why so many nas - because Right join, should those be zeros?
holc_comp |> filter(is.na(taxon))
holc_comp |> glimpse()
holc_comp |> group_by(id) |> count()

# MSA completeness and sampling density
msa_comp <-
  tibble(  filename = list.files('working_data/completeness_MSA', full.names = TRUE, recursive = TRUE)
         , file_contents = map(filename, ~read_csv(., col_types = cols()))) |> 
  mutate(taxon = str_remove(filename, 'working_data/completeness_MSA/') |> 
           str_remove('/Estimators.CSV') |> 
           str_remove('_graded') |> 
           str_remove('_not')) |> 
  separate(taxon, into = c('taxon', 'msa_GEOID'), sep = '/') |> #tabyl(taxon)
  separate(taxon, into = c('taxon', 'level')) |> 
  mutate( level = ifelse(is.na(level), 'species', level)
         , msa_GEOID = str_remove(msa_GEOID, 'msa_')) |> #tabyl(level, taxon)
  unnest(file_contents) |> 
  right_join(
    st_read('working_data/MSA_donut/msa_ungraded.gpkg', as_tibble = TRUE) |> 
      st_drop_geometry()
    , by = 'msa_GEOID'
  ) |> 
  mutate(  density = Records / area_msa_km2
         , holc_grade = 'MSA') |>  
  left_join(read_csv('working_data/MSA_UA_lookup.csv') |> 
              mutate(msa_GEOID = as.character(msa_GEOID)) |> 
              select(msa_GEOID, ua_GEOID)
            , by = 'msa_GEOID') |> 
  select(density, completeness = Completeness, pred_richness = Richness, holc_grade, taxon, level, ua_GEOID, msa_GEOID) # cosmetic reorder

msa_comp
msa_comp |> glimpse()
msa_comp |> group_by(msa_GEOID) |> count()
msa_comp |> group_by(ua_GEOID) |> count()


# UA completeness and sampling density
ua_comp <-
  tibble(  filename = list.files('working_data/completeness_UA', full.names = TRUE, recursive = TRUE)
         , file_contents = map(filename, ~read_csv(., col_types = cols()))) |> 
  mutate(taxon = str_remove(filename, 'working_data/completeness_UA/') |> 
           str_remove('/Estimators.CSV') |> 
           str_remove('_graded') |> 
           str_remove('_not')) |> 
  separate(taxon, into = c('taxon', 'ua_GEOID'), sep = '/') |> #tabyl(taxon)
  separate(taxon, into = c('taxon', 'level')) |> 
  mutate( level = ifelse(is.na(level), 'species', level)
         , ua_GEOID = str_remove(ua_GEOID, 'ua_')) |> #tabyl(level, taxon)
  unnest(file_contents) |>
  right_join(
    st_read('working_data/UA/UA_as_geopackage_2023-01-23 15-48-08.gpkg', as_tibble = TRUE) |> 
      st_drop_geometry() |> 
      select(ua_GEOID = GEOID, ua_area_km2)
    , by = 'ua_GEOID'
  ) |> 
  mutate(  density = Records / ua_area_km2
         , holc_grade = 'UA') |>  
  left_join(read_csv('working_data/MSA_UA_lookup.csv') |> mutate(msa_GEOID = as.character(msa_GEOID))
            , by = 'ua_GEOID') |>
  select(density, completeness = Completeness, pred_richness = Richness, holc_grade, taxon, level, ua_GEOID, msa_GEOID) # cosmetic reorder


ua_comp
ua_comp |> glimpse()
ua_comp |> group_by(msa_GEOID) |> count()
ua_comp |> group_by(ua_GEOID) |> count()


# mutate(holc_grade = factor(holc_grade, levels = c('A', 'B', 'C', 'D', 'UA', 'MSA')))

comp <- 
  bind_rows(holc_comp |> select(-id), msa_comp, ua_comp) |> 
  drop_na(taxon) |> 
  mutate(grade = factor(ifelse(level == 'species', holc_grade, paste0(holc_grade, ': family')),
         levels = c(  "A",  "A: family"
                    , "B",  "B: family"
                    , "C",  "C: family"
                    , "D",  "D: family"
                    , "UA", "UA: family"
                    , "MSA","MSA: family"), ordered = TRUE))


comp
comp |> View()
comp |> tabyl(holc_grade)
comp |> tabyl(holc_grade, taxon)
comp |> tabyl(holc_grade, taxon, level) |> bind_rows(.id = 'level') |> tibble() # HANDSOME TABLE!


# comp |> 
# # holc_comp |> 
#   drop_na(taxon) |> 
#   # ggplot(aes(holc_grade, density, fill = holc_grade)) +
#   ggplot(aes(grade, density, fill = grade)) +
#   geom_boxplot() +
#   scale_fill_manual(values = rep(holc_pal_f, 2)) + 
#   scale_y_log10() + 
#   theme_bw(16) + 
#   theme(axis.text.x = element_text(angle = 90)) + 
#   # facet_grid(level~taxon) +
#   # facet_grid(~taxon) +
#   facet_wrap(~taxon, scales = 'free') +
#   NULL

# THIS IS THE ONE
comp |> 
  drop_na(taxon) |> 
  # mutate(level = ifelse(level == 'species', ' ', level))|>
  mutate(level = ifelse(level == 'species', ' ', 'family: ')) |>
  ggplot(aes(interaction(level, holc_grade, sep = ''), density, fill = holc_grade
             # , color = level
         )) + 
  geom_boxplot() +
  theme_bw(16) + 
  scale_fill_manual(values = holc_pal_f) +
  scale_y_log10() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), legend.position = c(.85, .25)) +
  # scale_y_sqrt() +
  # facet_wrap(~interaction(taxon, level)) +
  labs(title = 'sampling density') + 
  facet_wrap(~taxon, scales = 'free', nrow = 2) +
  NULL

# COMPLETENESS
comp |> 
  drop_na(taxon) |> 
  # replace_na(list(completeness = 0)) |>
  # mutate(level = ifelse(level == 'species', ' ', level))|>
  mutate(level = ifelse(level == 'species', ' ', 'family: '))|> 
  ggplot(aes(interaction(level, holc_grade, sep = ''), completeness, fill = holc_grade
             # , color = level
         )) + 
  geom_boxplot() +
  theme_bw(16) + 
  scale_fill_manual(values = holc_pal_f) +
  scale_y_log10() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), legend.position = c(.85, .25)) +
  # scale_y_sqrt() +
  # facet_wrap(~interaction(taxon, level)) +
  labs(title = 'estimated completeness') + 
  facet_wrap(~taxon, scales = 'free', nrow = 2) +
  NULL


# RICHNESS
comp |> 
  drop_na(taxon) |> 
  # replace_na(list(completeness = 0)) |>
  # mutate(level = ifelse(level == 'species', ' ', level))|>
  mutate(level = ifelse(level == 'species', ' ', 'family: '))|> 
  ggplot(aes(interaction(level, holc_grade, sep = ''), pred_richness, fill = holc_grade
             # , color = level
         )) + 
  geom_boxplot() +
  theme_bw(16) + 
  scale_fill_manual(values = holc_pal_f) +
  scale_y_log10() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), legend.position = c(.85, .25)) +
  # scale_y_sqrt() +
  # facet_wrap(~interaction(taxon, level)) +
  labs(title = 'estimated RICHNESS') + 
  facet_wrap(~taxon, scales = 'free', nrow = 2) +
  NULL




# # need to get city/UA/MSA as random effect in there.. other covariates?
# comp |>
#   lm(formula = density ~ holc_grade*taxon + level) |> # sjPlot::plot_model(sort.est = TRUE)
#   broom::tidy(conf.int = TRUE) |> 
#   # ggplot(aes(estimate, term)) +
#   ggplot(aes(estimate, reorder(term, estimate))) +
#   geom_vline(xintercept = 0, color = 'dark gray') +
#   geom_point() + 
#   geom_errorbarh(aes(xmin = conf.low, xmax = conf.high)) +
#   labs(title = 'sampling density'
#        , subtitle = 'it is all about the birds') + 
#   theme_bw() + 
#   NULL


# need to get city/UA/MSA as random effect in there.. other covariates?
comp |>
  lme4::lmer(formula = density ~ holc_grade*taxon + level + (1 | msa_GEOID)) |> # sjPlot::plot_model(sort.est = TRUE)
  broom.mixed::tidy(conf.int = TRUE) |> # tabyl(effect)
  filter(effect == 'fixed') |> 
  ggplot(aes(estimate, reorder(term, estimate))) +
  geom_vline(xintercept = 0, color = 'dark gray') +
  geom_point() + 
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high)) +
  labs(title = 'sampling density AS MIXED model'
       , subtitle = 'it is all about the birds') + 
  theme_bw() + 
  NULL

# need to get city/UA/MSA as random effect in there.. other covariates?
comp |>
  drop_na(completeness) |> 
  # lm(formula = completeness ~ holc_grade*taxon + level) |> #sjPlot::plot_model(sort.est = TRUE)
  lme4::lmer(formula = completeness ~ holc_grade*taxon + level + (1 | msa_GEOID)) |> # sjPlot::plot_model(sort.est = TRUE)
  broom.mixed::tidy(conf.int = TRUE) |> # tabyl(effect)
  filter(effect == 'fixed') |> 
  ggplot(aes(estimate, reorder(term, estimate))) +
  geom_vline(xintercept = 0, color = 'dark gray') +
  geom_point() + 
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high)) +
  labs(title = 'Completeness'
       , subtitle = 'Whats the story here?') + 
  theme_bw() + 
  NULL


# completeness with NAs as zeros
comp |> 
  replace_na(list(completeness = 0)) |> 
  # lm(formula = completeness ~ holc_grade*taxon + level) |> #sjPlot::plot_model(sort.est = TRUE)
  # broom::tidy(conf.int = TRUE) |> 
  lme4::lmer(formula = completeness ~ holc_grade*taxon + level + (1 | msa_GEOID)) |> # sjPlot::plot_model(sort.est = TRUE)
  broom.mixed::tidy(conf.int = TRUE) |> # tabyl(effect)
  filter(effect == 'fixed') |> 
  ggplot(aes(estimate, reorder(term, estimate))) +
  geom_vline(xintercept = 0, color = 'dark gray') +
  geom_point() + 
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high)) +
  labs(title = 'Completeness - with NA changed to ZERO'
       , subtitle = 'Whats the story here?') + 
  theme_bw() + 
  NULL


preds <- 
  comp |> 
  # replace_na(list(completeness = 0)) |> 
  group_by(taxon, level) |> 
  nest() |> 
  # mutate(data        = map(data,  ~drop_na(.x))
  mutate(#  models_density = map(data, ~lm(density ~ holc_grade, .x))
         #, models_compl = map(data, ~lm(completeness ~ holc_grade, .x))
           models_density_msa = map(data, ~lme4::lmer(density ~ holc_grade + (1 | msa_GEOID), .x))
         , models_compl_msa   = map(data, ~lme4::lmer(completeness ~ holc_grade + (1 | msa_GEOID), .x))
         , models_rich_msa    = map(data, ~lme4::lmer(pred_richness ~ holc_grade + (1 | msa_GEOID), .x))
         
         , models_density_ua = map(data, ~lme4::lmer(density ~ holc_grade + (1 | ua_GEOID), .x))
         , models_compl_ua   = map(data, ~lme4::lmer(completeness ~ holc_grade + (1 | ua_GEOID), .x))
         , models_rich_ua    = map(data, ~lme4::lmer(pred_richness ~ holc_grade + (1 | ua_GEOID), .x))
         
         , ggpreds_density_msa = map(models_density_msa, ggeffects::ggpredict)
         , ggpreds_compl_msa   = map(models_compl_msa, ggeffects::ggpredict)
         , ggpreds_rich_msa    = map(models_rich_msa, ggeffects::ggpredict)
         
         , ggpreds_density_ua = map(models_density_ua, ggeffects::ggpredict)
         , ggpreds_compl_ua   = map(models_compl_ua, ggeffects::ggpredict)
         , ggpreds_rich_ua    = map(models_rich_ua, ggeffects::ggpredict)
         )

preds |> glimpse()

preds |>
  select(taxon, level, ggpreds_density_msa) |> 
  unnest(ggpreds_density_msa) |> 
  unnest(ggpreds_density_msa) |> 
  mutate(x = factor(x, levels = c('A', 'B', 'C', 'D', 'UA', 'MSA'))) |>
  ggplot(aes(x, predicted, color = level)) + 
  geom_hline(yintercept = 0, color = 'black') +
  geom_point(aes(shape = level), position = position_dodge(width = 0.5), size = 3) + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), position = position_dodge(width = 0.5), width = .3) +
  theme_bw(16) + 
  theme(legend.position = c(.75, .15)) +
  scale_color_viridis_d(direction = -1, option = 'B', begin = 0, end = .5) + 
  labs(title = 'sampling density with per-taxon models (9 in total)'
       , subtitle = 'birds are not representative!') + 
  facet_wrap(~taxon, scales = 'free_y') + 
  NULL


preds |>
  select(taxon, level, ggpreds_density_ua) |> 
  unnest(ggpreds_density_ua) |> 
  unnest(ggpreds_density_ua) |> 
  mutate(x = factor(x, levels = c('A', 'B', 'C', 'D', 'UA', 'MSA'))) |>
  ggplot(aes(x, predicted, color = level)) + 
  geom_hline(yintercept = 0, color = 'black') +
  geom_point(aes(shape = level), position = position_dodge(width = 0.5), size = 3) + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), position = position_dodge(width = 0.5), width = .3) +
  theme_bw(16) + 
  theme(legend.position = c(.75, .15)) +
  scale_color_viridis_d(direction = -1, option = 'B', begin = 0, end = .5) + 
  labs(title = 'sampling density with per-taxon models (9 in total) UA'
       , subtitle = 'birds are not representative!') + 
  facet_wrap(~taxon, scales = 'free_y') + 
  NULL



# completeness
preds |>
  select(taxon, level, ggpreds_compl_msa) |> 
  unnest(ggpreds_compl_msa) |> 
  unnest(ggpreds_compl_msa) |> 
  mutate(x = factor(x, levels = c('A', 'B', 'C', 'D', 'UA', 'MSA'))) |>
  ggplot(aes(x, predicted, color = level)) + 
  geom_point(aes(shape = level), position = position_dodge(width = 0.5), size = 2) + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), position = position_dodge(width = 0.5), width = .3) +
  theme_bw(16) + 
  theme(legend.position = c(.75, .15)) +
  scale_color_viridis_d(direction = -1, option = 'B', begin = 0, end = .5) + 
  labs(title = 'completeness witih per-taxon models (9 in total)'
       , subtitle = 'birds are not representative!') + 
  facet_wrap(~taxon) + 
  scale_y_continuous(expand = c(0, 0)
                     , limits = c(0, 100)
                     ) +
  NULL



# UA intercept
preds |>
  select(taxon, level, ggpreds_compl_ua) |> 
  unnest(ggpreds_compl_ua) |> 
  unnest(ggpreds_compl_ua) |> 
  mutate(x = factor(x, levels = c('A', 'B', 'C', 'D', 'UA', 'MSA'))) |>
  ggplot(aes(x, predicted, color = level)) + 
  geom_point(aes(shape = level), position = position_dodge(width = 0.5), size = 2) + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), position = position_dodge(width = 0.5), width = .3) +
  theme_bw(16) + 
  theme(legend.position = c(.75, .15)) +
  scale_color_viridis_d(direction = -1, option = 'B', begin = 0, end = .5) + 
  labs(title = 'completeness witih per-taxon models (9 in total) UA'
       , subtitle = 'birds are not representative!') + 
  facet_wrap(~taxon) + 
  scale_y_continuous(expand = c(0, 0)
                     , limits = c(0, 100)
                     ) +
  NULL


# MSA
preds |>
  select(taxon, level, ggpreds_rich_msa) |> 
  unnest(ggpreds_rich_msa) |> 
  unnest(ggpreds_rich_msa) |> 
  mutate(x = factor(x, levels = c('A', 'B', 'C', 'D', 'UA', 'MSA'))) |>
  ggplot(aes(x, predicted, color = level)) + 
  geom_point(aes(shape = level), position = position_dodge(width = 0.5), size = 2) + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), position = position_dodge(width = 0.5), width = .3) +
  theme_bw(16) + 
  theme(legend.position = c(.75, .15)) +
  scale_color_viridis_d(direction = -1, option = 'B', begin = 0, end = .5) + 
  labs(title = 'richness witih per-taxon models (9 in total) MSA'
       , subtitle = 'birds are not representative!') + 
  facet_wrap(~taxon, scales = 'free_y') + 
  # scale_y_continuous(expand = c(0, 0)
  #                    , limits = c(0, 100)
  #                    ) +
  NULL


# UA intercept richness
preds |>
  select(taxon, level, ggpreds_rich_ua) |> 
  unnest(ggpreds_rich_ua) |> 
  unnest(ggpreds_rich_ua) |> 
  mutate(x = factor(x, levels = c('A', 'B', 'C', 'D', 'UA', 'MSA'))) |>
  ggplot(aes(x, predicted, color = level)) + 
  geom_point(aes(shape = level), position = position_dodge(width = 0.5), size = 2) + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), position = position_dodge(width = 0.5), width = .3) +
  theme_bw(16) + 
  theme(legend.position = c(.75, .15)) +
  scale_color_viridis_d(direction = -1, option = 'B', begin = 0, end = .5) + 
  labs(title = 'richness witih per-taxon models (9 in total) UA'
       , subtitle = 'birds are not representative!') + 
  facet_wrap(~taxon, scales = 'free_y') + 
  # scale_y_continuous(expand = c(0, 0)
  #                    , limits = c(0, 100)
  #                    ) +
  NULL


  




```


# completeness
```{r}


# # get highly complete HOLC polygons
# tibble(  filename = list.files('working_data/completeness', full.names = TRUE, recursive = TRUE, pattern = 'Estimators.CSV')
#          , file_contents = map(filename, ~read_csv(., col_types = cols()))) |> 
#   mutate(taxon = str_remove(filename, 'working_data/completeness/') |> 
#            str_remove('/Estimators.CSV') |> 
#            str_remove('_only') |> 
#            str_remove('_graded')) |> 
#   select(taxon, file_contents) |> 
#   separate(taxon, into = c('taxon', 'level')) |> 
#   mutate(level = ifelse(is.na(level), 'species', level)) |> 
#   unnest(file_contents) |> 
#   right_join(holc, by = c('Area' = 'id')) |> 
#   # NA to zero on completeness
#   mutate(density = Records / area_holc_km2) |>  
#   left_join(read_csv('working_data/MSA/holc_msa_keys_2022-12-08 15-35-19.csv', col_types = 'cc') # makes type = character
#             , by = c('Area' = 'id')
#   ) |> 
#   left_join(read_csv('working_data/MSA_UA_lookup.csv') |> 
#               mutate(msa_GEOID = as.character(msa_GEOID)) |> 
#               select(msa_GEOID, ua_GEOID)
#             , by = 'msa_GEOID') |> 
#   select(id = Area, completeness = Completeness, taxon) |> 
#   filter(completeness > 80) |> 
#   write_csv(paste0('working_data/highly_complete_holcs/highly_complete_holcs_', Sys.Date(), '.csv'))

read_csv('working_data/highly_complete_holcs/highly_complete_holcs_2023-04-04.csv') |>
  ggplot(aes(completeness)) + geom_density()

# highly_complete <- read_csv('working_data/highly_complete_holcs/highly_complete_holcs_2023-03-02.csv')

(highly_complete_aves <-
  # read_csv('working_data/highly_complete_holcs/highly_complete_holcs_2023-03-02.csv') |> 
    read_csv('working_data/highly_complete_holcs/highly_complete_holcs_2023-04-04.csv') |> 
    filter(taxon == 'aves')) # ~10% of all HOLC polygons
  

(aves_files <- 
    list.files('../biodiversity_in_a_concrete_jungle_data_too_big/gbif_by_HOLC/aves'
               , full.names = TRUE))


# # sloppy but works (all of the columns, growing a vector [ewwey])
# # good to know though for when we want to look at non-graded areas!
# # UPDATE: will do non-graded 1 polygon at a time)
# tic(); for(i in 1:length(aves_files)){
#   print(i)
#   if(i == 1){ aves_holc <- read_fst(aves_files[i]) }
#   else      { aves_holc <- rbind(aves_holc, read_fst(aves_files[i])) }
#   }; toc(); beepr::beep() # ~2 mins
# 
# aves_holc |> dim() # 51,591,321 records!


# sloppy but works (all of the columns, growing a vector [ewwey])
tic(); for(i in 1:length(aves_files)){
  print(i)
  if(i == 1){
    
    aves_holc_highly_complete <- 
      read_fst(aves_files[i]) |> 
      tibble() |> 
      filter(id %in% highly_complete_aves$id) |> 
      distinct(id, taxon, family, genus, species) |> 
      select(id, everything())
    
    }
  else{
    
    aves_holc_highly_complete <- 
      rbind(aves_holc_highly_complete
            , read_fst(aves_files[i]) |> 
              tibble() |> 
              filter(id %in% highly_complete_aves$id) |> 
              distinct(id, taxon, family, genus, species) |> 
              select(id, everything())
      )
    }
  }; toc(); beepr::beep() # ~30 seconds


aves_holc_highly_complete |> 
  arrange(id) |> 
  write_csv(paste0('working_data/highly_complete_holcs_aves_species_lists/highly_complete_holcs_aves_species_lists_', Sys.Date(), '.csv'))





comp |> 
  select(completeness, taxon, msa_GEOID) |> 
  drop_na(completeness) |> 
  pivot_wider(msa_GEOID, names_from = taxon, values_from = completeness)

comp |> 
  select(completeness, taxon, msa_GEOID) |> 
  drop_na(completeness) |> 
  dplyr::group_by(msa_GEOID, taxon) %>%
  dplyr::summarise(n = dplyr::n(), .groups = "drop") %>%
  dplyr::filter(n > 1L) 
  


tibble(  filename = list.files('working_data/completeness', full.names = TRUE, recursive = TRUE, pattern = 'Estimators.CSV')
         , file_contents = map(filename, ~read_csv(., col_types = cols()))) |> 
  mutate(taxon = str_remove(filename, 'working_data/completeness/') |> 
           str_remove('/Estimators.CSV') |> 
           str_remove('_only') |> 
           str_remove('_graded')) |> 
  select(taxon, file_contents) |> 
  separate(taxon, into = c('taxon', 'level')) |> 
  mutate(level = ifelse(is.na(level), 'species', level)) |> 
  unnest(file_contents) |> 
  right_join(holc, by = c('Area' = 'id')) |> 
  # NA to zero on completeness
  mutate(density = Records / area_holc_km2) |>  
  left_join(read_csv('working_data/MSA/holc_msa_keys_2022-12-08 15-35-19.csv', col_types = 'cc') # makes type = character
            , by = c('Area' = 'id')
  ) |> 
  left_join(read_csv('working_data/MSA_UA_lookup.csv') |> 
              mutate(msa_GEOID = as.character(msa_GEOID)) |> 
              select(msa_GEOID, ua_GEOID)
            , by = 'msa_GEOID') |> 
  select(id = Area, completeness = Completeness, taxon) |> 
  drop_na(completeness) |> 
  pivot_wider(id, names_from = taxon, values_from = completeness, values_fn = mean) |> 
  select(-id) |> 
  cor(use = 'pairwise.complete.obs') |> 
  round(2) # life histories?





```


# get the non-graded MSA / UAs
```{r}

list.files('completeness_MSA')
list.files(full.names = TRUE, recursive = TRUE)




```




# link HOLC TO MSA (repeat for UA?)
```{r}
# which MSAs surround which UAs, and which holc polygons?

(holc_msa_keys <-
    read_csv('working_data/MSA/holc_msa_keys_2022-12-08 15-35-19.csv'
             , col_types = 'cc')) # makes type = character

st_read('../working_data/MSA_donut/msa_ungraded.gpkg', as_tibble = TRUE) |> 
      st_drop_geometry()


(ua_with_holc <- st_read('UA/UA_as_geopackage_2023-01-23 15-48-08.gpkg') |> rename(ua_GEOID = GEOID))


(ua_ids <- 
  st_read('working_data/UA/UA_as_geopackage_2023-01-23 15-48-08.gpkg') |> 
  st_drop_geometry() |> 
  tidylog::select(ua_GEOID = GEOID) |> 
  pull(ua_GEOID))

(ua_msa_int <- read_csv('working_data/MSA_UA_lookup.csv') |> 
  filter(ua_GEOID %in% ua_ids))


```










